name: Build & publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ---------- Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
